import { GameInfo } from '../types';

export const GAMES: GameInfo[] = [
  {
    id: 'wheel',
    title: 'Vòng quay may mắn',
    icon: '🎡',
    badge: 'Phổ biến',
    description: 'Vòng quay xoay tròn hồi hộp và dừng lại ở bạn học sinh may mắn',
    actionText: 'Quay vòng',
    bgAccent: 'from-amber-400/20 to-orange-500/20',
  },
  {
    id: 'mystery-gift',
    title: 'Hộp quà bí ẩn',
    icon: '🎁',
    badge: 'Hồi hộp',
    description: 'Nhiều hộp quà sắc màu rung lắc rồi bật mở công bố tên',
    actionText: 'Mở hộp quà',
    bgAccent: 'from-pink-500/20 to-rose-500/20',
  },
  {
    id: 'space-names',
    title: 'Tên bay trong không gian',
    icon: '🚀',
    badge: 'Khám phá',
    description: 'Phi thuyền vũ trụ lướt qua dải ngân hà hút lấy tên bạn học sinh',
    actionText: 'Dừng tàu vũ trụ',
    bgAccent: 'from-indigo-500/20 to-purple-600/20',
  },
  {
    id: 'star-catcher',
    title: 'Bắt ngôi sao kỳ diệu',
    icon: '⭐',
    badge: 'Lung linh',
    description: 'Bầu trời đêm đầy sao, một ngôi sao vàng bay đến tỏa sáng',
    actionText: 'Bắt ngôi sao',
    bgAccent: 'from-yellow-400/20 to-amber-500/20',
  },
  {
    id: 'train-express',
    title: 'Tàu hỏa gọi tên',
    icon: '🚂',
    badge: 'Vui nhộn',
    description: 'Đoàn tàu chở các toa tên học sinh xình xịch rồi phanh lại',
    actionText: 'Dừng đoàn tàu',
    bgAccent: 'from-emerald-400/20 to-teal-600/20',
  },
  {
    id: 'secret-door',
    title: 'Ai núp sau cánh cửa?',
    icon: '🚪',
    badge: 'Bí mật',
    description: 'Gõ cửa hoạt hình kỳ bí, mở ra bạn học sinh đang mỉm cười',
    actionText: 'Mở cửa ngẫu nhiên',
    bgAccent: 'from-blue-500/20 to-indigo-600/20',
  },
  {
    id: 'cloud-sky',
    title: 'Tên rơi từ trên trời',
    icon: '☁️',
    badge: 'Nhẹ nhàng',
    description: 'Đám mây bồng bềnh mang theo cầu vồng rực rỡ và tên bạn học sinh',
    actionText: 'Chọn đám mây',
    bgAccent: 'from-sky-400/20 to-blue-500/20',
  },
  {
    id: 'robot-helper',
    title: 'Robot chọn bạn',
    icon: '🤖',
    badge: 'Công nghệ',
    description: 'Chú Robot đáng yêu quét danh sách và hô vang tên bạn được gọi',
    actionText: 'Robot quét tên',
    bgAccent: 'from-cyan-400/20 to-blue-600/20',
  },
  {
    id: 'balloon-pop',
    title: 'Bong bóng nổ bụp',
    icon: '🎈',
    badge: 'Mới · Vui nhộn',
    description: 'Bong bóng sắc màu lơ lửng, phi tiêu thần kỳ làm nổ tung quả bóng chứa tên',
    actionText: 'Nổ bóng bay',
    bgAccent: 'from-pink-400/20 to-rose-500/20',
  },
  {
    id: 'claw-machine',
    title: 'Máy gắp thú bông',
    icon: '🧸',
    badge: 'Mới · Hồi hộp',
    description: 'Chiếc càng gắp kim loại hạ xuống gắp quả trứng vàng nở ra tên bạn học sinh',
    actionText: 'Hạ càng gắp',
    bgAccent: 'from-purple-400/20 to-indigo-500/20',
  },
  {
    id: 'speed-race',
    title: 'Đua xe siêu tốc',
    icon: '🏎️',
    badge: 'Mới · Gay cấn',
    description: 'Trường đua xe F1 kịch tính, chiếc xe vô địch cán đích mang theo tên học sinh',
    actionText: 'Xuất phát đua',
    bgAccent: 'from-red-500/20 to-amber-500/20',
  },
  {
    id: 'apple-tree',
    title: 'Cây táo vàng kỳ diệu',
    icon: '🍎',
    badge: 'Mới · Dễ thương',
    description: 'Cây đại thụ xum xuê, rung cành để quả táo vàng may mắn rơi vào giỏ',
    actionText: 'Rung cây táo',
    bgAccent: 'from-emerald-400/20 to-lime-500/20',
  },
  {
    id: 'treasure-island',
    title: 'Kho báu đại dương',
    icon: '🏴‍☠️',
    badge: 'Mới · Phiêu lưu',
    description: 'Rương báu cổ bên bờ biển sóng vỗ, tra chìa khóa vàng mở ra ngọc quý',
    actionText: 'Mở rương báu',
    bgAccent: 'from-amber-500/20 to-yellow-500/20',
  },
];
